# Generated by Django 6.0.8 on 2026-09-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_application', 'New Application Received'), ('application_status_changed', 'Application Status Updated'), ('application_withdrawn', 'Application Withdrawn'), ('opportunity_expired', 'Opportunity Expired'), ('opportunity_force_closed', 'Opportunity Force Closed'), ('opportunity_reopened', 'Opportunity Reopened'), ('provider_welcome', 'Welcome Provider'), ('provider_verified', 'Provider Verified'), ('provider_unverified', 'Provider Unverified')], max_length=50),
        ),
    ]
