from django.urls import path

from .views import (
    AdminMFAConfirmView,
    AdminMFADisableView,
    AdminMFASetupView,
    AdminMFAStatusView,
    AdminMFAVerifyView,
    ChangePasswordView,
    DecoratedTokenRefreshView,
    ForgotPasswordView,
    InvitationCreateView,
    InvitationDetailView,
    LoginView,
    LogoutView,
    PhoneLoginRequestOTPView,
    PhoneLoginVerifyOTPView,
    RequestOTPView,
    ResetPasswordView,
    StudentRegistrationView,
    UserProfileView,
    VerifyEmailView,
    VerifyOTPView,
)

app_name = "accounts"

urlpatterns = [
    path(
        "register/",
        StudentRegistrationView.as_view(),
        name="student-register",
    ),
    path(
        "verify-email/",
        VerifyEmailView.as_view(),
        name="verify-email",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "token/refresh/",
        DecoratedTokenRefreshView.as_view(),
        name="token-refresh",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "change-password/",
        ChangePasswordView.as_view(),
        name="change-password",
    ),
    path(
        "forgot-password/",
        ForgotPasswordView.as_view(),
        name="forgot-password",
    ),
    path(
        "reset-password/",
        ResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "request-otp/",
        RequestOTPView.as_view(),
        name="request-otp",
    ),
    path(
        "verify-otp/",
        VerifyOTPView.as_view(),
        name="verify-otp",
    ),
    path(
        "phone-login/request-otp/",
        PhoneLoginRequestOTPView.as_view(),
        name="phone-login-request-otp",
    ),
    path(
        "phone-login/verify-otp/",
        PhoneLoginVerifyOTPView.as_view(),
        name="phone-login-verify-otp",
    ),
    path(
        "profile/",
        UserProfileView.as_view(),
        name="user-profile",
    ),
    path(
        "admin/mfa/verify/",
        AdminMFAVerifyView.as_view(),
        name="admin-mfa-verify",
    ),
    path(
        "admin/mfa/setup/",
        AdminMFASetupView.as_view(),
        name="admin-mfa-setup",
    ),
    path(
        "admin/mfa/confirm/",
        AdminMFAConfirmView.as_view(),
        name="admin-mfa-confirm",
    ),
    path(
        "admin/mfa/disable/",
        AdminMFADisableView.as_view(),
        name="admin-mfa-disable",
    ),
    path(
        "admin/mfa/status/",
        AdminMFAStatusView.as_view(),
        name="admin-mfa-status",
    ),
    path(
        "invitations/",
        InvitationCreateView.as_view(),
        name="invitation-create",
    ),
    path(
        "invitations/<str:token>/",
        InvitationDetailView.as_view(),
        name="invitation-detail",
    ),
]