export const QUALIFICATION_CHOICES = [
  { value: '', label: 'Select Qualification' },
  { value: 'degree', label: 'Degree' },
  { value: 'diploma', label: 'Diploma' },
  { value: 'certificate', label: 'Certificate' },
  { value: 'self_taught', label: 'Self Taught' },
  { value: 'other', label: 'Other' },
];

export const AVAILABILITY_CHOICES = [
  { value: 'immediate', label: 'Immediate' },
  { value: '1_week', label: 'Within 1 Week' },
  { value: '2_weeks', label: 'Within 2 Weeks' },
  { value: '1_month', label: 'Within 1 Month' },
  { value: 'flexible', label: 'Flexible' },
];

export const ORGANIZATION_TYPE_CHOICES = [
  { value: 'company', label: 'Company' },
  { value: 'startup', label: 'Startup' },
  { value: 'cafe', label: 'Cafe' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'shop', label: 'Shop / Retail' },
  { value: 'ngo', label: 'NGO / Non-Profit' },
  { value: 'educational_institution', label: 'Educational Institution' },
  { value: 'freelancer', label: 'Freelancer' },
  { value: 'individual', label: 'Individual' },
  { value: 'event_organizer', label: 'Event Organizer' },
  { value: 'other', label: 'Other' },
];

export const STUDENT_FIELD_CONFIG = [
  {
    key: 'full_name',
    label: 'Full Name',
    tab: 'header',
    type: 'text',
    placeholder: 'e.g. Alex Johnson',
    isBaseUserField: true,
    required: true,
  },
  {
    key: 'profession',
    label: 'Profession / Headline',
    tab: 'about',
    type: 'text',
    placeholder: 'e.g. Frontend Engineer & UI Designer',
  },
  {
    key: 'bio',
    label: 'Bio / Summary',
    tab: 'overview',
    type: 'textarea',
    placeholder: 'Share your background, passions, and goals...',
  },
  {
    key: 'skills',
    label: 'Skills',
    tab: 'overview',
    type: 'tags',
    placeholder: 'e.g. React, Python, Figma, Tailwind',
  },
  {
    key: 'languages',
    label: 'Languages Spoken',
    tab: 'overview',
    type: 'tags',
    placeholder: 'e.g. English, Hindi, Spanish',
  },
  {
    key: 'qualification_type',
    label: 'Qualification Type',
    tab: 'about',
    type: 'select',
    options: QUALIFICATION_CHOICES,
  },
  {
    key: 'qualification_name',
    label: 'Qualification / Degree Name',
    tab: 'about',
    type: 'text',
    placeholder: 'e.g. B.Tech Computer Science',
  },
  {
    key: 'institution',
    label: 'Institution / College',
    tab: 'about',
    type: 'text',
    placeholder: 'e.g. Stanford University',
  },
  {
    key: 'availability',
    label: 'Availability',
    tab: 'about',
    type: 'select',
    options: AVAILABILITY_CHOICES,
  },
  {
    key: 'city',
    label: 'City / Location',
    tab: 'about',
    type: 'text',
    placeholder: 'e.g. San Francisco, CA',
  },
  {
    key: 'portfolio_url',
    label: 'Portfolio Website',
    tab: 'portfolio',
    type: 'url',
    placeholder: 'https://alexjohnson.dev',
  },
  {
    key: 'phone_number',
    label: 'Primary Phone Number',
    tab: 'settings',
    type: 'phone',
    placeholder: '+1 555-0199',
    isBaseUserField: true,
  },
  {
    key: 'whatsapp_number',
    label: 'WhatsApp Contact Number',
    tab: 'settings',
    type: 'phone',
    placeholder: '+1 555-0199',
  },
  {
    key: 'show_phone',
    label: 'Show Phone Number publicly on applications',
    tab: 'settings',
    type: 'checkbox',
  },
  {
    key: 'show_whatsapp',
    label: 'Show WhatsApp Contact publicly on applications',
    tab: 'settings',
    type: 'checkbox',
  },
  {
    key: 'social_links',
    label: 'Social Profiles & Links',
    tab: 'settings',
    type: 'social',
  },
];

export const PROVIDER_FIELD_CONFIG = [
  {
    key: 'organization_name',
    label: 'Organization / Business Name',
    tab: 'header',
    type: 'text',
    placeholder: 'e.g. Acme Tech Solutions',
    required: true,
  },
  {
    key: 'description',
    label: 'Organization Overview & Bio',
    tab: 'overview',
    type: 'textarea',
    placeholder: 'Describe your organization, mission, and culture...',
  },
  {
    key: 'organization_type',
    label: 'Organization Type',
    tab: 'about',
    type: 'select',
    options: ORGANIZATION_TYPE_CHOICES,
  },
  {
    key: 'contact_person',
    label: 'Primary Contact Person',
    tab: 'about',
    type: 'text',
    placeholder: 'e.g. Sarah Connor (Head of Talent)',
  },
  {
    key: 'address',
    label: 'Office / Physical Address',
    tab: 'about',
    type: 'text',
    placeholder: 'e.g. 500 Market St, Suite 300',
  },
  {
    key: 'city',
    label: 'City / Location',
    tab: 'about',
    type: 'text',
    placeholder: 'e.g. New York, NY',
  },
  {
    key: 'website',
    label: 'Official Website',
    tab: 'portfolio',
    type: 'url',
    placeholder: 'https://acmetech.com',
  },
  {
    key: 'phone_number',
    label: 'Organization Phone Number',
    tab: 'settings',
    type: 'phone',
    placeholder: '+1 555-0199',
    isBaseUserField: true,
  },
  {
    key: 'whatsapp_number',
    label: 'WhatsApp Contact Number',
    tab: 'settings',
    type: 'phone',
    placeholder: '+1 555-0199',
  },
  {
    key: 'show_phone',
    label: 'Display Phone Number publicly on posted opportunity listings',
    tab: 'settings',
    type: 'checkbox',
  },
  {
    key: 'show_whatsapp',
    label: 'Display WhatsApp Contact publicly on posted opportunity listings',
    tab: 'settings',
    type: 'checkbox',
  },
  {
    key: 'social_links',
    label: 'Social Media Profiles & Web',
    tab: 'settings',
    type: 'social',
  },
];
