# Generated by Django 6.0.8 on 2026-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Target phone number for OTP verification.', max_length=20, verbose_name='phone number')),
                ('otp_hash', models.CharField(help_text='Hashed OTP value for secure verification.', max_length=128, verbose_name='OTP hash')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('registration', 'Registration'), ('password_reset', 'Password Reset'), ('mfa', 'Multi-Factor Authentication')], help_text='Intended workflow purpose for this OTP.', max_length=20, verbose_name='purpose')),
                ('expires_at', models.DateTimeField(help_text='Expiration timestamp for the OTP.', verbose_name='expires at')),
                ('is_used', models.BooleanField(default=False, help_text='Flag indicating whether the OTP has already been verified/used.', verbose_name='is used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'phone OTP',
                'verbose_name_plural': 'phone OTPs',
                'db_table': 'phone_otps',
                'ordering': ['-created_at'],
            },
        ),
    ]
