# Generated by Django 6.0.8 on 2026-08-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(help_text='Base32 TOTP secret key for authenticator app verification.', max_length=64, verbose_name='TOTP secret')),
                ('is_enabled', models.BooleanField(default=False, help_text='Flag indicating whether MFA is active for this admin account.', verbose_name='is enabled')),
                ('backup_codes', models.JSONField(default=list, help_text='Hashed single-use emergency recovery codes.', verbose_name='backup codes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(help_text='Admin user associated with these MFA settings.', on_delete=django.db.models.deletion.CASCADE, related_name='mfa_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin MFA setting',
                'verbose_name_plural': 'admin MFA settings',
                'db_table': 'admin_mfa',
            },
        ),
    ]
