# Generated by Django 6.0.8 on 2026-08-12 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminmfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique cryptographically secure token string.', max_length=64, unique=True, verbose_name='invitation token')),
                ('is_used', models.BooleanField(default=False, help_text='Flag indicating whether the invitation has been accepted.', verbose_name='is used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp for the invitation token.', null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('invited_user', models.ForeignKey(blank=True, help_text='New user account created via this invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitation', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='User who generated the invitation link.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
