# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('company', 'Company'), ('startup', 'Startup'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('shop', 'Shop'), ('ngo', 'NGO'), ('educational_institution', 'Educational Institution'), ('freelancer', 'Freelancer'), ('individual', 'Individual'), ('event_organizer', 'Event Organizer'), ('other', 'Other')], default='company', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verification flag for provider organization.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider profile',
                'verbose_name_plural': 'provider profiles',
                'db_table': 'provider_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
