# Generated by Django 6.0.8 on 2026-09-08 05:50

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_providerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Path to stored resume file.', upload_to=apps.accounts.models.resume_upload_to_path, verbose_name='uploaded file')),
                ('original_filename', models.CharField(help_text='Original filename provided during upload.', max_length=255, verbose_name='original filename')),
                ('file_size', models.PositiveIntegerField(help_text='Size of uploaded file in bytes.', verbose_name='file size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='Detected MIME content type.', max_length=100, verbose_name='MIME type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when resume was initially uploaded.', verbose_name='uploaded at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when resume was last updated/replaced.', verbose_name='updated at')),
                ('user', models.OneToOneField(help_text='Student user owner of this resume.', on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'db_table': 'resumes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
