# Generated by Django 6.0.8 on 2026-09-10 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('provider_verified', 'Provider Verified'), ('provider_unverified', 'Provider Unverified'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('opportunity_force_closed', 'Opportunity Force Closed'), ('opportunity_deleted', 'Opportunity Deleted')], help_text='Categorical type of admin action performed.', max_length=50)),
                ('target_description', models.CharField(help_text="Human-readable target details (e.g., 'Provider: Acme Corp', 'User: test@example.com').", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(help_text='Admin user who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin action log',
                'verbose_name_plural': 'admin action logs',
                'db_table': 'admin_action_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
