# Generated by Django 6.0.8 on 2026-09-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adminactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('provider_verified', 'Provider Verified'), ('provider_unverified', 'Provider Unverified'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('opportunity_force_closed', 'Opportunity Force Closed'), ('opportunity_reopened', 'Opportunity Reopened'), ('opportunity_deleted', 'Opportunity Deleted')], help_text='Categorical type of admin action performed.', max_length=50),
        ),
    ]
