# Generated by Django 6.0.8 on 2026-09-14 04:44

import apps.accounts.validators
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_adminactionlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/providers/%Y/%m/', validators=[apps.accounts.validators.validate_profile_picture_file], verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='show phone number'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='show_whatsapp',
            field=models.BooleanField(default=False, verbose_name='show WhatsApp number'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='social links'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp number'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/students/%Y/%m/', validators=[apps.accounts.validators.validate_profile_picture_file], verbose_name='profile picture')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='profession')),
                ('qualification_type', models.CharField(blank=True, choices=[('degree', 'Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('self_taught', 'Self-Taught'), ('other', 'Other')], max_length=50, verbose_name='qualification type')),
                ('qualification_name', models.CharField(blank=True, max_length=200, verbose_name='qualification name')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='institution')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name='availability')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='city')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='portfolio URL')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp number')),
                ('show_phone', models.BooleanField(default=False, verbose_name='show phone number')),
                ('show_whatsapp', models.BooleanField(default=False, verbose_name='show WhatsApp number')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='social links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
                'db_table': 'student_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
