# Generated by Django 6.0.8 on 2026-09-03 08:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('part_time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('startup_hiring', 'Startup Hiring'), ('project_collaboration', 'Project Collaboration'), ('tutoring', 'Tutoring'), ('volunteer', 'Volunteer'), ('event_based', 'Event Based')], max_length=50)),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('stipend', 'Stipend'), ('unpaid', 'Unpaid')], max_length=20)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=20)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'opportunity',
                'verbose_name_plural': 'opportunities',
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category', 'city'], name='opp_status_cat_city_idx')],
            },
        ),
    ]
