# Generated by Django 6.0.8 on 2026-09-10 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('owner_closed', 'Owner Closed'), ('admin_moderated', 'Admin Moderated'), ('expired', 'Expired')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_opportunities', to=settings.AUTH_USER_MODEL),
        ),
    ]
