# Generated by Django 6.0.8 on 2026-09-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_close_reason_opportunity_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('startup_hiring', 'Startup Hiring'), ('project_collaboration', 'Project Collaboration'), ('tutoring', 'Tutoring'), ('volunteer', 'Volunteer'), ('event_based', 'Event Based')], max_length=50),
        ),
    ]
