# Generated by Django 6.0.8 on 2026-09-21 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_alter_opportunity_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='opportunities.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recommended opportunity',
                'verbose_name_plural': 'recommended opportunities',
                'db_table': 'recommended_opportunities',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
    ]
